services:
  postgres:
    image: postgres:16
    container_name: fleet_postgres
    environment:
      POSTGRES_USER: fleet_user
      POSTGRES_PASSWORD: fleet_pass
      POSTGRES_DB: fleet_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: